server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: asset-management

  datasource:
    url: jdbc:mysql://database:3306/asset_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&autoReconnect=true
    username: asset
    password: asset
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          'time_zone': Asia/Ho_Chi_Minh

  mail:
    host: smtp.gmail.com
    port: 587
    username: xthinh04052002@gmail.com
    password: ydrorszesavmhorv
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 86400 # second 24h
  refreshable-duration: 2592000 #seconds 30 ngày
  issuer: "Thinh_GJaa"
