server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: asset-management

  datasource:
    url: jdbc:mysql://localhost:3306/asset_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


