server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: asset-management

  datasource:
    url: jdbc:mysql://localhost:3306/asset_db?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: dd-MM-yyyy HH:mm:ss


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 86400 # second 24h
  refreshable-duration: 2592000 #seconds 30 ngày
  issuer: "Thinh_GJaa"
