server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asset_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&CreateDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      INDENT_OUTPUT: true
    time-zone: Asia/Ho_Chi_Minh

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.concentrix.asset: DEBUG

# Cấu hình các profile (nếu dùng)
# ---
# spring:
#   profiles: dev
#   datasource:
#     url: jdbc:mysql://localhost:3306/asset_management_dev?useSSL=false&serverTimezone=UTC

# Thêm các cấu hình khác nếu cần
